# Generated by Django 5.2.3 on 2025-06-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Назва пристрою')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_of_metrics', models.CharField(max_length=40, verbose_name='Тип метрики')),
                ('value_of_metrics', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('battery_level', models.PositiveSmallIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.devices')),
            ],
        ),
    ]
