# Generated by Django 5.2.3 on 2025-06-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва пристрою')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('humidity', models.PositiveSmallIntegerField(blank=True)),
                ('illumination', models.PositiveSmallIntegerField(blank=True)),
                ('pressure', models.PositiveSmallIntegerField(blank=True)),
                ('air_quality', models.PositiveSmallIntegerField(blank=True)),
                ('carbon_dioxide_level', models.PositiveSmallIntegerField(blank=True)),
                ('wind_velocity', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('noise', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('battery_level', models.PositiveSmallIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.devices')),
            ],
        ),
    ]
