# Generated by Django 5.2.3 on 2025-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='type_of_metrics',
            field=models.CharField(max_length=50, verbose_name='Тип метрики'),
        ),
    ]
