# Generated by Django 5.2.3 on 2025-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_metrics_type_of_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='value_of_metrics',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
