# Generated by Django 5.2.3 on 2025-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_metrics_value_of_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
