# Generated by Django 5.2.3 on 2025-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_rename_type_of_metrics_metrics_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='type',
            field=models.CharField(max_length=35, verbose_name='Тип метрики'),
        ),
    ]
