# Generated by Django 5.2.3 on 2025-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_metrics_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
